#!/usr/bin/env node
// GENERATED by Whetstone's emitter from .sdd/lanes.yaml (ADR-0005).
// Do NOT edit by hand — change lanes.yaml and regenerate.
//
// BLOCKING, unlike strict-path-guard.mjs which only warns. That difference is the
// point: treehouse isolates worktrees, but nothing stops a crewmate editing a
// shared contract inside its own worktree. A boundary that relies on the agent
// choosing to respect it is advisory, and advisory rules are what this project
// exists to replace.
//
// Activated by a `.wst-lane` file at the worktree root, or WST_LANE=<id> which
// takes precedence. Neither present => orchestrator, no restriction.
//
// Hook API grounded against code.claude.com/docs/en/hooks (2026-08-07):
// PreToolUse blocks via hookSpecificOutput.permissionDecision="deny" and MUST
// exit 0 — JSON output is only processed on exit 0. (See sig-0003: a previous
// hook here was built on an unverified reading of this same API.)
import fs from "node:fs";
import path from "node:path";

// Compiled from .sdd/lanes.yaml. See `matches` below for the entry forms.
const SHARED = [
  "src/core/checks/schema.ts",
  "src/core/contracts.ts",
  "src/core/ports.ts",
  "src/cli.ts",
  "package.json",
  "tsconfig.json",
  "tsconfig.build.json",
  ".sdd/",
  ".claude/",
];

const LANES = {
  triage: ["src/core/triage/", "src/commands/triage.ts"],
  receipts: ["src/core/receipts/", "src/shell/receipts*"],
  gate: ["src/core/gate/", "src/commands/gate.ts"],
  annotate: ["src/core/annotate/", "src/commands/pr.ts", "src/shell/github.ts"],
  init: ["src/core/init/", "src/commands/init.ts"],
  fixtures: ["test/fixtures/", "scripts/calibrate.ts"],
};

// "foo/" = directory prefix · "foo*" = string prefix · otherwise exact file match.
// The `*` form exists because an exact match on `src/shell/receipts.ts` also denied
// the adjacent `receipts.test.ts`, leaving an adapter with no way to be tested.
const matches = (rel, entry) => {
  if (entry.endsWith("/")) return rel.startsWith(entry);
  if (entry.endsWith("*")) return rel.startsWith(entry.slice(0, -1));
  return rel === entry;
};

function deny(reason) {
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: reason,
      },
    })
  );
  process.exit(0); // JSON output is only processed on exit 0
}

let input;
try {
  input = JSON.parse(fs.readFileSync(0, "utf-8"));
} catch {
  process.exit(0); // never break the tool on a malformed payload
}

const fp = input?.tool_input?.file_path ?? "";
if (!fp) process.exit(0); // not a path-based edit

// Resolve the repo root FROM THE FILE BEING EDITED, walking up to find `.sdd/`.
// Deliberately not CLAUDE_PROJECT_DIR: a crewmate works inside a treehouse
// worktree, which is a different root from the orchestrator's project dir. Keying
// off the caller's project dir made every worktree edit look "outside the repo"
// and silently allowed everything — a guard that fails OPEN is worse than none,
// because you believe you are protected.
function findRoot(startPath) {
  let dir = path.dirname(path.resolve(startPath));
  for (;;) {
    if (fs.existsSync(path.join(dir, ".sdd"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

const root = findRoot(fp);
if (!root) process.exit(0); // not inside a Whetstone repo — not this guard's business

// The worktree IS the lane, so the lane marker lives in the worktree. Env var
// wins when set (that is how a spawned `claude` process will be told), file
// otherwise (works for any agent editing in that tree).
let lane = process.env.WST_LANE ?? "";
if (!lane) {
  try {
    lane = fs.readFileSync(path.join(root, ".wst-lane"), "utf-8").trim();
  } catch {
    /* no marker */
  }
}
if (!lane) process.exit(0); // orchestrator

const owned = LANES[lane];
if (!owned) {
  deny(
    `lane "${lane}" is not a known lane. Known lanes: ${Object.keys(LANES).join(", ")}. ` +
      `Fix .wst-lane or WST_LANE before editing anything — an unknown lane has no boundary.`
  );
}

const rel = path.relative(root, path.resolve(fp));
if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) process.exit(0);

if (SHARED.some((entry) => matches(rel, entry))) {
  deny(
    `BLOCKED: ${rel} is a SHARED CONTRACT, not owned by any lane (you are in lane "${lane}").\n` +
      `Changing it invalidates what the other lanes are building against, so it is a ` +
      `conversation, not a commit. Report what you need and why; the orchestrator decides.\n` +
      `Your lane owns: ${owned.join(", ")}`
  );
}

if (!owned.some((entry) => matches(rel, entry))) {
  deny(
    `BLOCKED: ${rel} is outside lane "${lane}".\n` +
      `Your lane owns: ${owned.join(", ")}\n` +
      `If the work genuinely needs this file, the lane split is wrong — say so instead of ` +
      `working around it. Two lanes editing one file is the collision this guard prevents.`
  );
}

process.exit(0); // in-lane: allow
