import { describe, expect, it } from "vitest";
import { editConfig } from "./edit.js";

const FILE = `# Whetstone config. Generated by \`wst init\`; safe to edit by hand.
version: 0
agent: claude             # which adapter runs llm checks
backend: files            # files = self-contained, git-native, zero deps
memory:
  namespace: "acme"
retro:
  suggest_after: 5        # signals
skills:                   # ACTIVE skills; the emitter references only these
  - skills/delegation.md
  - skills/lazy.md
  # Inactive for this project. The file is on disk either way; uncomment to enable.
  # - skills/voice.md
`;

describe("editConfig — a surgical edit, never a re-render", () => {
  it("switches the judge in place", () => {
    expect(editConfig(FILE, { agent: "gemini" })).toContain("agent: gemini");
  });

  it("keeps the comment that sat beside the value it changed", () => {
    // A re-render would drop it, and the comment is what tells the next reader
    // what the key is for.
    expect(editConfig(FILE, { agent: "gemini" })).toContain("# which adapter runs llm checks");
  });

  it("preserves every key it was not asked to change", () => {
    const out = editConfig(FILE, { agent: "gemini" });
    for (const line of ["version: 0", "backend: files", 'namespace: "acme"', "suggest_after: 5"]) {
      expect(out).toContain(line);
    }
  });

  it("activates a skill by uncommenting the line already there", () => {
    const out = editConfig(FILE, { skills: ["skills/delegation.md", "skills/lazy.md", "skills/voice.md"] });
    expect(out).toMatch(/^ {2}- skills\/voice\.md$/m);
    expect(out).not.toMatch(/^ {2}# - skills\/voice\.md$/m);
  });

  it("deactivates a skill by commenting it, never by deleting it", () => {
    // Deleting loses the file's existence from the config, and the only way back
    // would be to remember the name.
    const out = editConfig(FILE, { skills: ["skills/delegation.md"] });
    expect(out).toMatch(/^ {2}# - skills\/lazy\.md$/m);
    expect(out).toContain("skills/lazy.md");
  });

  it("leaves the file byte-identical when nothing was asked", () => {
    expect(editConfig(FILE, {})).toBe(FILE);
  });

  it("leaves the file byte-identical when the value is already what was asked", () => {
    expect(editConfig(FILE, { agent: "claude" })).toBe(FILE);
  });

  it("refuses a file with no agent key rather than inventing one", () => {
    // Appending a key to a file whose shape we did not parse is how an edit
    // lands in the wrong block.
    expect(() => editConfig("version: 0\n", { agent: "gemini" })).toThrow(/agent/);
  });

  it("refuses a skill it cannot find a line for", () => {
    expect(() => editConfig(FILE, { skills: ["skills/nope.md"] })).toThrow(/nope/);
  });
});
