import { describe, expect, it } from "vitest";
import { editConfig } from "./edit.js";

const FILE = `# Whetstone config. Generated by \`wst init\`; safe to edit by hand.
version: 0
agent: claude             # which adapter runs llm checks
backend: files            # files = self-contained, git-native, zero deps
memory:
  namespace: "acme"
retro:
  suggest_after: 5        # signals
skills:                   # ACTIVE skills; the emitter references only these
  - skills/delegation.md
  - skills/lazy.md
  # Inactive for this project. The file is on disk either way; uncomment to enable.
  # - skills/voice.md
`;

describe("editConfig — a surgical edit, never a re-render", () => {
  it("switches the judge in place", () => {
    expect(editConfig(FILE, { agent: "antigravity" })).toContain("agent: antigravity");
  });

  it("keeps the comment that sat beside the value it changed", () => {
    // A re-render would drop it, and the comment is what tells the next reader
    // what the key is for.
    expect(editConfig(FILE, { agent: "antigravity" })).toContain("# which adapter runs llm checks");
  });

  it("preserves every key it was not asked to change", () => {
    const out = editConfig(FILE, { agent: "antigravity" });
    for (const line of ["version: 0", "backend: files", 'namespace: "acme"', "suggest_after: 5"]) {
      expect(out).toContain(line);
    }
  });

  it("activates a skill by uncommenting the line already there", () => {
    const out = editConfig(FILE, { skills: ["skills/delegation.md", "skills/lazy.md", "skills/voice.md"] });
    expect(out).toMatch(/^ {2}- skills\/voice\.md$/m);
    expect(out).not.toMatch(/^ {2}# - skills\/voice\.md$/m);
  });

  it("deactivates a skill by commenting it, never by deleting it", () => {
    // Deleting loses the file's existence from the config, and the only way back
    // would be to remember the name.
    const out = editConfig(FILE, { skills: ["skills/delegation.md"] });
    expect(out).toMatch(/^ {2}# - skills\/lazy\.md$/m);
    expect(out).toContain("skills/lazy.md");
  });

  it("leaves the file byte-identical when nothing was asked", () => {
    expect(editConfig(FILE, {})).toBe(FILE);
  });

  it("leaves the file byte-identical when the value is already what was asked", () => {
    expect(editConfig(FILE, { agent: "claude" })).toBe(FILE);
  });

  it("adds a missing agent key at the TOP level, never inside a nested block", () => {
    // The risk the old refusal was guarding: a key appended to a file whose shape
    // nobody parsed lands under whatever block the cursor happened to be in, and
    // `memory:\n  agent: claude` means nothing.
    const nested = "version: 0\nmemory:\n  namespace: \"x\"\n";
    const out = editConfig(nested, { agent: "antigravity" }).split("\n");
    const at = out.findIndex((l) => l.startsWith("agent:"));

    expect(at).toBeGreaterThanOrEqual(0);
    expect(out[at]).not.toMatch(/^\s/);
    expect(out.slice(0, at).some((l) => l.startsWith("memory:"))).toBe(false);
  });

  it("refuses a skill it cannot find a line for", () => {
    expect(() => editConfig(FILE, { skills: ["skills/nope.md"] })).toThrow(/nope/);
  });
});

/**
 * A config with no `agent:` key is a config `wst config` can still change.
 *
 * It threw, and the throw came out of an interactive menu as a Node stack trace
 * with internal paths in it. A menu that offers an option has to be able to
 * carry it out or say why not; the file simply predates the key.
 */
describe("editConfig — a key the file does not have yet", () => {
  const noAgent = "# Whetstone config.\nversion: 0\nbackend: files\nskills:\n  - skills/voice.md\n";

  it("adds the key rather than refusing, and keeps the rest of the file", () => {
    const out = editConfig(noAgent, { agent: "antigravity" });

    expect(out).toMatch(/^agent: antigravity/m);
    expect(out).toContain("backend: files");
    expect(out).toContain("  - skills/voice.md");
  });

  it("puts it where `init` writes it, under `version:`, so the file still reads in order", () => {
    const lines = editConfig(noAgent, { agent: "claude" }).split("\n");

    expect(lines[lines.indexOf("version: 0") + 1]).toMatch(/^agent: claude/);
  });

  it("adds it to a file with no `version:` either, without losing a line", () => {
    const bare = "backend: files\n";
    const out = editConfig(bare, { agent: "claude" });

    expect(out).toMatch(/^agent: claude/m);
    expect(out).toContain("backend: files");
  });

  it("still edits in place where the key IS there, rather than adding a second", () => {
    const out = editConfig("version: 0\nagent: claude\n", { agent: "antigravity" });

    expect(out.match(/^agent:/gm)).toHaveLength(1);
    expect(out).toMatch(/^agent: antigravity/m);
  });

  it("throws nothing, ever, for a caller that cannot catch it usefully", () => {
    for (const text of ["", "\n", "nonsense"]) {
      expect(() => editConfig(text, { agent: "claude" })).not.toThrow();
    }
  });
});
