/**
 * The payload: everything `init` writes that is not the triage compiler's output.
 *
 * The constraint that shapes every string in this file is **ADR-0004: the payload
 * must be self-contained.** All of this travels into someone else's repository. A
 * sentence here that says "see Whetstone's SPEC" produces a dangling reference in
 * a repo that has never heard of Whetstone, and the agent reading it either
 * hallucinates the missing file or gives up on the rule. That has already happened
 * once in this project's history, which is why `selfcontained.ts` exists and why
 * `planInit` refuses to return a plan that violates it.
 *
 * Two consequences visible below:
 *
 * - `MEMORY_README` restates the signal and ADR schemas IN FULL rather than citing
 *   them. Duplication is the correct trade when the alternative is a broken link.
 * - The retro is described inline in `AGENTS.md`. The Wizard-of-Oz template said
 *   "run the retro (see `retro.md`)", but `retro.md` is a Whetstone document and
 *   does not exist in the target — that reference is exactly the bug class the ADR
 *   names, so it is not reproduced here.
 */

import { DEFINITION_DIR } from "../paths.js";
import type { CopyRequest } from "./artifact.js";
import type { StackFacts } from "./detect.js";
import { renderRiskProfile, type RiskProfile } from "./interview.js";

/**
 * All eight ship, always — a skill left out cannot be switched on later without a
 * re-init. The *active* set is calibration, and it lives in `wst.yaml`.
 */
export const SKILL_FILES: readonly string[] = Object.freeze([
  "delegation.md",
  "tdd-discipline.md",
  "doc-locations.md",
  "token-economy.md",
  "recording.md",
  "voice.md",
  "lazy.md",
  "xreview.md",
]);

const SKILL_BLURBS: Readonly<Record<string, string>> = {
  "delegation.md": "inline vs delegate to a fresh-context sub-agent",
  "tdd-discipline.md": "how much test rigor each triage tier buys",
  "doc-locations.md": "where a new `.md` belongs — team-shared vs personal",
  "token-economy.md": "keep context lean across sessions and sub-agents",
  "recording.md": "what to save to memory, when, and who confirms the write",
  "voice.md": "how the agent engages you: anti-pleaser, verify before agreeing",
  "lazy.md": "minimal-first: does this need to exist? reuse before adding",
  "xreview.md": "adversarial fresh-context review on high-stakes changes",
};

export function skillCopies(): readonly CopyRequest[] {
  return SKILL_FILES.map((name) => ({
    from: `skills/${name}`,
    to: `${DEFINITION_DIR}/skills/${name}`,
  }));
}

/**
 * Which skills are ON at init: all of them.
 *
 * Deactivation is calibration, not deletion — a rule that does not apply to this
 * project still costs context every session it is loaded — and `wst.yaml` is
 * where it happens, by hand, listing the inactive ones as comments.
 *
 * WHAT USED TO BE HERE: `doc-locations` was switched off for a repo whose commit
 * log named one author, on the theory that a solo project has no team/personal
 * split. That was a guess about how a project WORKS read off a headcount, and
 * ADR-0016 took it out with the rest of the inference. Nothing asks for it now,
 * and "on" is the answer the old code already gave whenever the count was
 * unknown: absence of evidence was never evidence of solo work.
 */
export function activeSkills(): readonly string[] {
  return SKILL_FILES.map((name) => `skills/${name}`);
}

export interface WstYamlInput {
  readonly backend: string;
  readonly skills: readonly string[];
  /** Namespace for any memory adapter. Derived from the repo, never shared. */
  readonly namespace: string;
}

export function renderWstYaml(input: WstYamlInput): string {
  const active = new Set(input.skills);
  const inactive = SKILL_FILES.map((n) => `skills/${n}`).filter((s) => !active.has(s));

  const lines = [
    "# Whetstone config. Generated by `wst init`; safe to edit by hand.",
    "version: 0",
    `backend: ${input.backend}            # files = self-contained, git-native, zero deps`,
    "memory:",
    "  # Pins the namespace for any memory adapter. NEVER share a namespace with another",
    "  # project: cross-contaminated memory is worse than none, because it looks like recall.",
    `  namespace: ${JSON.stringify(input.namespace)}`,
    "retro:",
    "  suggest_after: 5        # signals",
    "skills:                   # ACTIVE skills — the emitter references only these",
    ...input.skills.map((s) => `  - ${s}`),
  ];

  if (inactive.length > 0) {
    lines.push(
      "  # Inactive for this project. The file is on disk either way — uncomment to enable.",
      ...inactive.map((s) => `  # - ${s}`),
    );
  }

  return `${lines.join("\n")}\n`;
}

export interface ConstitutionInput {
  readonly repoName: string;
  readonly date: string;
  readonly purpose: string;
  readonly risk: RiskProfile;
  readonly conventions: readonly string[];
  /** What the repo declares about itself. Read, never guessed. */
  readonly detected: StackFacts;
  /** What somebody SAID the project is built with. Null until anyone says. */
  readonly declared: string | null;
}

/**
 * The two halves of the stack section, kept visibly apart.
 *
 * Above the line is a sentence a person or a judge wrote and signed. Below it is
 * what `init` read, each item next to the file it came from. Merging them into
 * one bullet list is how "counted 40 `.ts` files" ends up reading exactly like
 * "the owner told us it is TypeScript".
 */
function stackSection(detected: StackFacts, declared: string | null): string {
  const stated =
    declared === null || declared.trim().length === 0
      ? "**Not stated.** `wst init` reads what this repo declares — its scripts, its lockfile —\n" +
        "and it does not guess what the code is written in. Fill this in; nothing downstream\n" +
        "depends on it, and a reader does."
      : declared.trim();

  const read = [
    `- **Package manager:** ${detected.packageManager ?? "not declared anywhere init could read"}`,
    `- **Tests:** ${detected.commands.test ?? "no runner declared"}`,
    `- **Typecheck:** ${detected.commands.typecheck ?? "none declared"}`,
    `- **Lint:** ${detected.commands.lint ?? "none declared"}`,
    `- **Test files present at init:** ${detected.hasTests ? "yes" : "no"}`,
  ].join("\n");

  return `${stated}\n\nRead off this repo's own files at init, and correctable here:\n\n${read}`;
}

export function renderConstitution(input: ConstitutionInput): string {
  const stackFacts = stackSection(input.detected, input.declared);

  const conventions =
    input.conventions.length > 0
      ? input.conventions.map((c) => `- ${c}`).join("\n")
      : [
          "- Code, configuration and comments in English.",
          "- Commit style not yet established — pick one and record it here.",
        ].join("\n");

  return `---
id: constitution
generated: ${input.date}
status: active
---
# ${input.repoName} — constitution

Governance for this project. Every other file under \`${DEFINITION_DIR}/\` is calibrated against it.

**\`${DEFINITION_DIR}/constitution.md\` is amended by an explicit human edit and by nothing else.** The retro may
propose changes to the triage rules, the skills and the checks; it never touches the
constitution. A project whose definition of "correct" can be rewritten by the tool that
enforces it does not have a definition of correct.

## Purpose

${input.purpose.trim()}

## Risk profile

${renderRiskProfile(input.risk)}

## Non-negotiables

1. Every rule in this repo carries a receipt — the signal or decision that created it.
   A rule nobody can trace is a rule nobody can retire.
2. State that matters is plain text in git. No rule depends on a server being up.
3. A judgment check earns its \`block\`. A deterministic check may block freely; a check
   that depends on a model's opinion is capped at a warning until it has been measured
   against known-good and known-bad examples and agreed with itself every time.
4. Corrections are appended, never overwritten. \`${DEFINITION_DIR}/memory/signals.jsonl\` is
   append-only; an ADR is superseded rather than rewritten.

## Stack facts

${stackFacts}

## Conventions

${conventions}
`;
}

/** The memory schema, restated in full — the first of the two consequences above. */
export const MEMORY_README = `# Memory — how to log

This directory is the project's memory. It is plain text in git, it is append-only,
and it is the input to every retro. **Everything an agent needs in order to log
correctly is written down here** — there is nothing to look up elsewhere.

## \`signals.jsonl\` — append-only, one JSON object per line

A signal is a moment the agent went off-track and got corrected, or a near-miss. Log
the small ones too; that is the point. A retro over five sharp signals produces a real
rule, a retro over none produces a plausible one.

| field | required | notes |
|-------|----------|-------|
| \`id\` | yes | \`sig-\` + zero-padded counter, e.g. \`sig-0001\` |
| \`ts\` | yes | ISO 8601 datetime |
| \`type\` | yes | kebab-case, open vocabulary: \`wrong-cwd\`, \`triage-miss\`, \`test-skip\`, \`scope-creep\`, \`context-blowout\`, … |
| \`phase\` | yes | \`init\` \\| \`triage\` \\| \`plan\` \\| \`apply\` \\| \`verify\` \\| \`review\` \\| \`other\` |
| \`severity\` | yes | \`low\` \\| \`medium\` \\| \`high\` |
| \`detail\` | yes | one or two sentences a human can reconstruct the event from |
| \`branch\` | no | the git branch it happened on — the unit of work. Read from git, never guessed from a ticket id. Omit it rather than writing \`null\` |
| \`rule_affected\` | no | skill file(s) implicated, e.g. \`["skills/delegation.md"]\` |
| \`supersedes\` | no | id of an earlier entry this one corrects |
| \`resolved_by\` | no | filled by the retro: the amendment that addressed this signal |

**Never edit or delete a line.** A correction is a NEW entry carrying \`supersedes\`.
The one exception is \`resolved_by\`, which the retro may set on an existing line — it
records which amendment answered the signal, not what happened.

Example:

\`\`\`
{"id":"sig-0001","ts":"2026-01-15T14:30:00Z","type":"wrong-cwd","phase":"apply","severity":"high","detail":"Sub-agent ran a destructive command at the repo root instead of the package directory.","branch":"feat/import-csv","rule_affected":["skills/delegation.md"]}
\`\`\`

## \`decisions.md\` — one anchored entry per decision

\`### adr-NNNN — the decision\`, then a meta line carrying status, date and any signals
that earned it, then **what was rejected and why**. That last part is the reason the
record exists: a rejected option leaves no commit, so git cannot reconstruct it. The
page itself says the rest.

**Accepted text is never rewritten.** A decision that turned out wrong is superseded —
its status moves, its prose stays. The value of the record is that it shows what was
believed at the time, and editing it destroys exactly that.

## \`out-of-scope/\` — what was deliberately refused

One file per capability this project was asked for and decided not to build. A
refusal that lives only in memory gets re-proposed every few months with the
argument re-derived from scratch. Each entry says what was asked, why it is out of
scope, what escape hatches already exist, and the request that prompted it. Empty
until something is actually refused; the directory's own README has the form.

## \`patterns.md\` and \`retro-log.md\`

\`patterns.md\` holds distilled recurring patterns — the output of a retro, not raw
observation. \`retro-log.md\` records that a retro happened, which signals it read, and
what it changed, so the next one knows where to start.

## The loop

Signals are data; decisions are prose. Both feed the retro: read the new signals,
cluster them, and decide what apparatus each cluster earns — amend a rule, add a check,
retire one that never fires. **The analysis is automatic; the write is not.** A human
confirms every change to a rule, because a tool that can silently rewrite the standard
it enforces against you is not a standard.
`;

/**
 * The fourth memory artifact (ADR-0012).
 *
 * `memory/` records what went wrong (`signals.jsonl`), what was decided
 * (`decisions/`) and what was proposed (`proposals/`, `retro-log.md`). Nothing
 * recorded what was deliberately REFUSED, and a refusal with no file gets
 * re-proposed every six months with the argument re-derived from scratch — by a
 * fresh agent that has no way to know the conversation already happened.
 *
 * The attribution is INLINE rather than a pointer to Whetstone's LICENSE, per the
 * payload rule in the header.
 */
export const OUT_OF_SCOPE_README = `# Out of scope

Things this project was asked for and decided NOT to build.

A refusal that lives only in someone's memory gets re-proposed every few months,
and the argument gets re-derived from scratch every time — usually worse, because
the pressure that produced the original answer is no longer in the room. This
directory is where a "no" keeps its reasoning.

One file per refusal, \`kebab-case-name.md\`, and each one states four things:

1. **What was asked** — the capability, in the words of whoever wanted it. Not a
   strawman: if the request cannot be stated in a form its author would recognise,
   it has not been understood well enough to refuse.
2. **Why it is out of scope** — the reasoning, at the time, with the constraint or
   the tradeoff that decided it.
3. **What escape hatches already exist** — how someone who needs this can get it
   today. A refusal with no alternative is usually a missing feature wearing a
   decision's clothes.
4. **The request that prompted it** — the date and the context, so a reader can
   tell a one-off from a pattern. The fourth time the same thing is asked for, the
   answer probably deserves revisiting.

A "no" recorded here is not permanent. It is reviewable, which is the opposite of
forgotten: what reverses it is new evidence, and the file is where the next person
starts rather than where they stop.

Empty until something is actually refused. An invented entry would be a decision
nobody made.

---

The form of this directory is borrowed from \`mattpocock/skills\` (MIT licensed),
whose \`.out-of-scope/\` is the same idea.
`;

export const DECISIONS_MD = `---
id: decisions
ts: YYYY-MM-DD
status: active
origin: []
---
# Decisions

One entry per decision, in the order they were taken. Each carries **only what was ruled
out and why** — that is the part git cannot reconstruct, because a rejected option has no
commit. What the decision made easier, and how it was implemented, are in the history.

Every entry opens with a meta line: status, the date it was taken, and any signals that
earned it.

\`\`\`
### adr-NNNN — the decision, as a sentence in the present tense
\`accepted\` · YYYY-MM-DD · signals: sig-0001

Rejected: the option that lost, and the reason it lost. An entry that names no
rejected option recorded a preference, not a decision.
\`\`\`

**Status is how a decision is amended.** It moves \`proposed\` → \`accepted\` →
\`superseded by adr-NNNN\`. The prose above it is never rewritten; later commentary goes
in a new entry, not into an old one's voice.

**The bar for writing one at all:** would someone propose the losing option again in
three months? If not, the commit message is enough.
`;

export const CLAUDE_MD = `@AGENTS.md
`;

export interface AgentsMdInput {
  readonly repoName: string;
  /** Full text of the generated constitution; its sections are inlined. */
  readonly constitution: string;
  /** Full text of the generated triage-rules.md; its table is inlined. */
  readonly triageRulesMd: string;
  readonly activeSkills: readonly string[];
  readonly checkIds: readonly string[];
}

/** Everything after the frontmatter and the H1. */
function bodyOf(markdown: string): string {
  const withoutFrontmatter = markdown.replace(/^---\n[\s\S]*?\n---\n/, "");
  return withoutFrontmatter.replace(/^#[^\n]*\n/, "").trim();
}

export function renderAgentsMd(input: AgentsMdInput): string {
  const skills = input.activeSkills
    .map((path) => {
      const name = path.split("/").pop() ?? path;
      const blurb = SKILL_BLURBS[name];
      return `- \`${DEFINITION_DIR}/${path}\`${blurb === undefined ? "" : ` — ${blurb}`}`;
    })
    .join("\n");

  const checks =
    input.checkIds.length > 0
      ? `The gate runs: ${input.checkIds.map((id) => `\`${id}\``).join(", ")}. Each one is a\n` +
        `file under \`${DEFINITION_DIR}/checks/\` explaining what it is for and what to do when it fails.`
      : `No checks are registered yet. Add one under \`${DEFINITION_DIR}/checks/<id>.md\` when a class of\n` +
        "mistake proves worth catching automatically — not before.";

  return `# ${input.repoName} — agent workflow

> **GENERATED from \`${DEFINITION_DIR}/\`. Do not edit by hand.** Everything below is a rendering of
> files under \`${DEFINITION_DIR}/\`, which is the source of truth. Editing \`AGENTS.md\` changes nothing
> durable: the next regeneration overwrites it, and the rule you meant to change is
> still whatever \`${DEFINITION_DIR}/\` says.
>
> Every section below names its source file explicitly rather than referring to itself,
> because the same sentence is true in its source and false here.

## Constitution

${bodyOf(input.constitution)}

## How changes are triaged

${bodyOf(input.triageRulesMd)}

## Verification

${checks}

## Active skills

Read the file before acting when its trigger matches. These are rules, not suggestions;
each one exists because something went wrong without it.

${skills}

## Recording what happens

This is the part that makes the rest improve rather than rot.

- **Something goes wrong** — the agent takes a wrong turn and gets corrected, or nearly
  does — append a line to \`${DEFINITION_DIR}/memory/signals.jsonl\`. The schema is in
  \`${DEFINITION_DIR}/memory/README.md\`. Log the small ones; they are the ones that reveal patterns.
- **A decision gets made** — add an entry to \`${DEFINITION_DIR}/memory/decisions.md\`, following
  the shape that page describes.
- **Periodically** — run a retro: read the signals logged since the last one, cluster
  them, and decide what each cluster earns (amend a triage rule, add or retire a check,
  sharpen a skill). Record the outcome in \`${DEFINITION_DIR}/memory/retro-log.md\`.

**The analysis is automatic; the write is not.** A human confirms every change to a
rule. Nothing in this repo rewrites its own standard.
`;
}
