/**
 * The payload: everything `init` writes that is not the triage compiler's output.
 */

import { DEFINITION_DIR } from "../paths.js";
import type { CopyRequest } from "./artifact.js";
import type { StackFacts } from "./detect.js";
import { renderRiskProfile, type RiskProfile } from "./interview.js";

/**
 * All eight ship, always — a skill left out cannot be switched on later without a
 * re-init. The *active* set is calibration, and it lives in `wst.yaml`.
 */
/**
 * @param texts what the shell read off Whetstone's own `skills/`, keyed by `from`.
 *   Absent entries leave `contents` unset, which `auditSelfContained` reports as
 *   unaudited rather than clean.
 */
/**
 * A skill as it should land in someone else's repo.
 *
 * The rule travels; the argument that produced it does not. A changelog entry
 * says "v4 (adr-0014, sig-0041)" — a decision and a signal that exist in
 * Whetstone's record and in no bootstrapped repo, so every line of it is a
 * dangling reference under ADR-0004. It is replaced by one line naming where the
 * rule came from, and the target repo's own retro grows the log from there.
 *
 * The frontmatter stays: `version:` is what an update compares against.
 */
export interface WstYamlInput {
  readonly backend: string;
  /** Namespace for any memory adapter. Written only where one is configured. */
  readonly namespace?: string;
  /**
   * Skills to declare active. Absent in a new installation, which has none: the
   * readiness path reads no skill, so a registry of them would be a list of files
   * that are not there.
   */
  readonly skills?: readonly string[];
  /**
   * The adapter that runs llm checks. Omitted, and omitted from the file too: a
   * new installation seeds no lens, so naming a judge would configure a thing that
   * does not exist.
   */
  readonly agent?: string;
}

export function renderWstYaml(input: WstYamlInput): string {
  const lines = [
    "# Whetstone config. Generated by `wst init`; safe to edit by hand.",
    "version: 0",
    `backend: ${input.backend.padEnd(17)} # files = self-contained, git-native, zero deps`,
  ];
  // A memory namespace in a repo with no memory is a setting for something that is
  // not installed, and a reader cannot tell it from one that matters.

  // Written only where there is something to write. A key naming a judge in a repo
  // with no lens, or a skills list in a repo with no skills, is configuration for a
  // thing that is not installed.
  if (input.agent !== undefined) {
    lines.splice(2, 0, `agent: ${input.agent.padEnd(18)} # which adapter runs llm checks`);
  }
  if (input.namespace !== undefined) {
    lines.push(
      "memory:",
      "  # Never share a namespace across projects: cross-contaminated memory is",
      "  # worse than none, because it looks like recall.",
      `  namespace: ${JSON.stringify(input.namespace)}`,
    );
  }
  const skills = input.skills ?? [];
  if (skills.length > 0) {
    lines.push("skills:                   # ACTIVE skills; the emitter references only these");
    for (const s of skills) lines.push(`  - ${s}`);
  }

  return `${lines.join("\n")}\n`;
}

/**
 * `.wst/.gitignore` — per-machine runtime state `init` writes but that a clone
 * must never inherit committed. The reasoning is Whetstone's own (its top-level
 * `.gitignore` explains each of these three at length); restated here rather than
 * cited, per ADR-0004: a target repo has never heard of Whetstone's tree.
 *
 * `memory/signals.jsonl` is deliberately absent: that page is committed on
 * purpose, and an init-written gitignore that swallowed it would silently stop a
 * team from sharing the one thing this whole layer exists to accumulate.
 */
export function renderWstGitignore(): string {
  return `# Whetstone runtime state. Regenerated on every run, never commit it.

# Compiled check index: regenerable from ${DEFINITION_DIR}/checks/*.md via \`wst check --compile\`.
# A compiled artifact that can silently go stale is the same trap as trusting a
# version string for identity.
checks/_index.json

# Receipts are a derived cache: "check X passed on this exact input". Regenerable,
# and a stale one would claim a pass that never happened for the current code.
# Worse than stale if committed: a receipt authorises skipping a check, so every
# clone would inherit skips it never earned, one of them possibly a paid judge
# call.
receipts/
`;
}

/** Written at the repo root by `init --propose`, and never committed. */
export const ROOT_GITIGNORE_ENTRIES: readonly string[] = Object.freeze([".wst-answers.json"]);

/**
 * The stanza `init` ensures is present in the target repo's OWN `.gitignore`.
 *
 * Unlike \`.wst/.gitignore\` this cannot be a plain generated file: the entries
 * live at the repo root, and almost every repo already has a root
 * \`.gitignore\` with content worth keeping. The shell reads it and appends only
 * what is missing (source: \`src/commands/init.ts\`) rather than treating a
 * pre-existing \`.gitignore\` as a collision.
 *
 * @param entries defaults to all of them; pass only the ones missing from a
 *   \`.gitignore\` that already has some of this stanza, so a re-run does not
 *   duplicate a line.
 */
export function renderRootGitignoreStanza(
  entries: readonly string[] = ROOT_GITIGNORE_ENTRIES,
): string {
  return `# The draft \`wst init --propose\` writes for you to edit and sign. It is a
# working file and not a definition: what the repo keeps is \`${DEFINITION_DIR}/\`,
# which the draft was only used to generate.
${entries.join("\n")}
`;
}
