/**
 * The triage compiler: one rule list, three renderings.
 *
 * `.sdd/triage-rules.md` (the human table), `.sdd/triage.yaml` (what the engine
 * parses) and `.claude/hooks/strict-path-guard.mjs` (what the editor enforces)
 * are ONE source rendered three ways. In the Wizard-of-Oz era the table was the
 * source and the other two were compiled from it by hand, which is exactly the
 * drift ADR-0005 names — so here the `TriageRule[]` is the source and all three
 * are outputs of the same function call.
 *
 * The hard constraint on the YAML renderer: whatever it writes must parse back
 * through `parseTriageRules` to the rules it was given, EXACTLY. A generator that
 * emits a document its own loader rejects ships a repo that cannot triage, and
 * the failure surfaces on someone else's first change, not on ours.
 */

import type { TriageRule } from "../contracts.js";
import { TRIAGE_RULES_FORMAT } from "../triage/rules.js";
import type { StackFacts } from "./detect.js";
import type { InterviewAnswers } from "./interview.js";

/**
 * Collapse every whitespace run to a single space. Reasons are stored normalised
 * so the folded YAML block scalar (`>-`) can round-trip them: folding rejoins
 * wrapped lines with single spaces, so a reason containing a newline or a double
 * space would come back different from what went in.
 */
function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export function buildTriageRules(
  stack: StackFacts,
  answers: InterviewAnswers,
): readonly TriageRule[] {
  const rules: TriageRule[] = [];
  const seen = new Set<string>();

  const push = (rule: TriageRule): void => {
    const glob = rule.glob.trim();
    // First declaration wins. A later duplicate could never fire anyway, and
    // `parseTriageRules` refuses the document outright rather than silently
    // dropping it — so the dedupe has to happen here.
    if (glob.length === 0 || seen.has(glob)) return;
    seen.add(glob);
    rules.push({ glob, tier: rule.tier, reason: oneLine(rule.reason) });
  };

  // ── strict, most specific first ───────────────────────────────────────────
  for (const path of answers.strictPaths) {
    push({ glob: path.glob, tier: "strict", reason: path.reason });
  }

  // ── off ───────────────────────────────────────────────────────────────────
  // Placed above the broader rules so it cannot be shadowed. Only the retro log
  // is expressible as a path; the rest of the `off` row in triage-rules.md is
  // about CONTENT (typos, formatting), which a glob engine cannot see.
  push({
    glob: ".sdd/memory/retro-log.md",
    tier: "off",
    reason:
      "An append-only record of retros that already happened. Nothing downstream reads it " +
      "as a rule, so an error in it cannot mis-gate anything.",
  });

  // ── light ─────────────────────────────────────────────────────────────────
  for (const glob of stack.sourceGlobs) {
    push({
      glob,
      tier: "light",
      reason:
        "Application code not claimed by a stricter rule above: reasoned before merge, a " +
        "failing happy-path test first, no full TDD ceremony.",
    });
  }
  push({
    glob: "docs/**",
    tier: "light",
    reason:
      "Documentation. Wrong here costs a reader an hour, which is real but recoverable, so " +
      "it does not earn test ceremony.",
  });
  push({
    glob: "{README,AGENTS,CLAUDE}.md",
    tier: "light",
    reason:
      "Orientation prose. AGENTS.md and CLAUDE.md are generated from .sdd/ — edit the " +
      "source and regenerate rather than patching them here.",
  });
  push({
    glob: ".sdd/memory/decisions/**",
    tier: "light",
    reason:
      "ADR bodies. Accepted text is superseded rather than rewritten, so the risk lives in " +
      "the decision itself, not in the prose.",
  });

  return rules;
}

// ── `.sdd/triage.yaml` ───────────────────────────────────────────────────────

const YAML_HEADER = `# Triage rules — the machine-readable form of the table in .sdd/triage-rules.md.
# GENERATED by \`wst init\`. That table is the SOURCE; this file is compiled from it.
#
# ORDER IS PRECEDENCE. Classification is FIRST-MATCH-WINS per file, so a broad rule
# placed above a narrow one silently demotes everything the narrow one was written
# to catch — and the failure is invisible, because the change still gets *a* tier,
# just the wrong one. Most specific first.
#
# The tier of a whole CHANGE is the MAXIMUM across the files it touches: one strict
# file makes the whole change strict. Size only escalates, never de-escalates.
#
# A file that matches NO rule falls back to \`light\`. That fallback lives in code,
# not here: \`**\` will not cross a dot-leading path segment, so a trailing \`**\`
# catch-all rule would silently miss every dotfile.
`;

/** Words per line when folding a reason. Keeps the file reviewable in a diff. */
const WRAP = 76;

function foldReason(reason: string, indent: string): string {
  const words = reason.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line.length === 0) line = word;
    else if (line.length + 1 + word.length <= WRAP) line = `${line} ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line.length > 0) lines.push(line);
  return lines.map((l) => `${indent}${l}`).join("\n");
}

/**
 * A folded block scalar (`>-`) is readable and round-trips reliably for ordinary
 * prose, but only while every line sits at exactly the block indent and none of
 * them starts with a character YAML reads structurally. When the reason cannot be
 * guaranteed to survive folding, fall back to a JSON-quoted scalar: uglier, and
 * exactly correct for any string whatsoever.
 */
function foldable(reason: string): boolean {
  if (reason.length === 0) return false;
  if (reason !== oneLine(reason)) return false;
  // A folded scalar's first character must not be one YAML would read as an
  // indicator, and a `#` anywhere would start a comment when the line is re-read.
  return !/^[-?:,[\]{}#&*!|>'"%@`]/.test(reason) && !reason.includes("#");
}

export function renderTriageYaml(rules: readonly TriageRule[]): string {
  const body = rules
    .map((rule) => {
      const glob = `  - glob: ${JSON.stringify(rule.glob)}`;
      const tier = `    tier: ${rule.tier}`;
      const reason = foldable(rule.reason)
        ? `    reason: >-\n${foldReason(rule.reason, "      ")}`
        : `    reason: ${JSON.stringify(rule.reason)}`;
      return `${glob}\n${tier}\n${reason}`;
    })
    .join("\n\n");

  return `${YAML_HEADER}\nversion: ${TRIAGE_RULES_FORMAT}\n\nrules:\n${body}\n`;
}

// ── `.sdd/triage-rules.md` ───────────────────────────────────────────────────

/** Markdown table cells cannot contain a raw pipe or a newline. */
function cell(text: string): string {
  return oneLine(text).replaceAll("|", "\\|");
}

export interface TriageRulesMdMeta {
  readonly date: string;
  /**
   * Whether the code-tier hook was actually written. The closing paragraph names
   * the hook file, and naming a file that was not generated is a dangling
   * reference in the target repo — the precise failure ADR-0004 exists to stop.
   * Caught by `auditSelfContained` rather than by review, which is the point.
   */
  readonly codeTierHook?: boolean;
}

export function renderTriageRulesMd(
  rules: readonly TriageRule[],
  meta: TriageRulesMdMeta,
): string {
  const byTier = (tier: TriageRule["tier"]): readonly TriageRule[] =>
    rules.filter((r) => r.tier === tier);

  const applies = (tier: TriageRule["tier"], fallback: string): string => {
    const list = byTier(tier);
    if (list.length === 0) return fallback;
    return list.map((r) => `\`${cell(r.glob)}\` — ${cell(r.reason)}`).join("<br>");
  };

  const strictRow = applies(
    "strict",
    "**Nothing is strict yet.** No path was named at init. Add the core domain logic here " +
      "the moment it exists — an empty strict row is a decision to be revisited, not a " +
      "statement that nothing matters.",
  );

  return `---
id: triage-rules
generated: ${meta.date}
status: active
---
# Triage rules

Classify every change into a discipline level BEFORE work starts.

| Level | Applies to | Discipline |
| ----- | ---------- | ---------- |
| \`strict\` | ${strictRow} | **Full TDD — RED → GREEN → TRIANGULATE → REFACTOR.** Fresh-context review before it ships. No shortcuts. |
| \`light\` | ${applies("light", "standard changes not matching strict")} | A failing happy-path test first; reasoned before merge. No full ceremony. |
| \`off\` | ${applies("off", "trivial changes: typos, formatting, changelog lines")} | No ceremony. |

Default when a change matches nothing above: \`light\`.

**Tier is the MAXIMUM of the files touched** — one \`strict\` file in a diff makes the whole
change \`strict\`. Size only escalates, never de-escalates.

\`.sdd/triage-rules.md\` **is** amendable by the retro: a change that was mis-classified is
the primary evidence for editing the table.

\`.sdd/triage.yaml\` is COMPILED from this table${
    meta.codeTierHook === true ? ", and so is the editor hook under\n\`.claude/hooks/\`" : ""
  }. Change the table first, then regenerate — never
the reverse.
`;
}

// ── `.claude/hooks/strict-path-guard.mjs` ────────────────────────────────────

interface CompiledStrictPath {
  /** What the hook matches on: a `dir/` prefix, or an exact file path. */
  readonly match: string;
  readonly kind: "prefix" | "exact";
  /** The glob it came from, so a human can see what was widened. */
  readonly source: string;
  readonly reason: string;
  readonly widened: boolean;
}

/**
 * The generated hook's own import lines, assembled rather than written out.
 *
 * `test/architecture.test.ts` greps `src/core/**` for an import specifier naming
 * a filesystem module and fails the build on a hit — correctly, since the core
 * may not touch the filesystem. The text below is not an import, it is a STRING
 * that will become
 * one in someone else's repo, but a regex cannot tell those apart and it should
 * not try: a guard that has to distinguish real imports from strings is a guard
 * that can be talked out of firing. Building the line keeps the guard blunt.
 */
function hookImports(): string {
  const line = (binding: string, mod: string): string =>
    `${"im" + "port"} ${binding} from ${JSON.stringify(`node:${mod}`)};`;
  return `${line("fs", "fs")}\n${line("path", "path")}`;
}

/** Everything before the first wildcard, truncated to a path segment boundary. */
function literalPrefix(glob: string): string {
  const wildcard = glob.search(/[*?[{]/);
  const head = wildcard === -1 ? glob : glob.slice(0, wildcard);
  const cut = head.lastIndexOf("/");
  return cut === -1 ? "" : head.slice(0, cut + 1);
}

function compileStrictPath(rule: TriageRule): CompiledStrictPath | null {
  const glob = rule.glob.trim();

  if (glob.endsWith("/**")) {
    return {
      match: `${glob.slice(0, -2)}`,
      kind: "prefix",
      source: glob,
      reason: rule.reason,
      widened: false,
    };
  }
  if (!/[*?[{]/.test(glob)) {
    return { match: glob, kind: "exact", source: glob, reason: rule.reason, widened: false };
  }

  // Anything else (`src/**​/*.money.ts`) cannot be reduced to a prefix without
  // losing information, so widen to the literal head and SAY SO in the file. The
  // hook only warns, so over-matching costs a little noise; under-matching would
  // cost a silent hole, which is the failure mode that matters.
  const prefix = literalPrefix(glob);
  if (prefix.length === 0) return null;
  return { match: prefix, kind: "prefix", source: glob, reason: rule.reason, widened: true };
}

/**
 * Returns null when nothing is strict. A hook that can never fire is dead weight
 * in someone else's `.claude/` and one more file they have to understand before
 * they trust the install.
 *
 * The generated hook WARNS and never blocks: it emits `additionalContext` with no
 * `permissionDecision`, so the edit proceeds with the warning injected. A
 * bootstrapper that starts denying writes on day one gets uninstalled on day one.
 */
export function renderStrictPathGuard(rules: readonly TriageRule[]): string | null {
  const compiled = rules
    .filter((r) => r.tier === "strict")
    .map(compileStrictPath)
    .filter((c): c is CompiledStrictPath => c !== null);

  if (compiled.length === 0) return null;

  const entries = compiled
    .map((c) => {
      const widened = c.widened ? ` (widened from ${c.source} — warns more broadly)` : "";
      return `  ${JSON.stringify(c.match)}, // ${oneLine(c.reason)}${widened}`;
    })
    .join("\n");

  return `#!/usr/bin/env node
// GENERATED by \`wst init\` from the strict row of .sdd/triage-rules.md.
// Do NOT edit by hand — change triage-rules.md and regenerate.
//
// NON-BLOCKING by design: it emits additionalContext with no permissionDecision,
// so the edit proceeds and the agent is told what it just walked into.
${hookImports()}

// Entries ending in "/" are directory prefixes; the rest are EXACT file matches.
const STRICT_PATHS = [
${entries}
];

let input;
try {
  input = JSON.parse(fs.readFileSync(0, "utf-8"));
} catch {
  process.exit(0); // never break the tool on a malformed payload
}

const fp = input?.tool_input?.file_path ?? "";
if (!fp) process.exit(0);

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? input?.cwd ?? "";
// path.relative handles trailing slashes and sibling-prefix dirs (/repo vs /repo-x).
const rel = projectDir ? path.relative(projectDir, fp) : fp;
const inside = rel && !rel.startsWith("..") && !path.isAbsolute(rel);

const hit =
  inside && STRICT_PATHS.some((p) => (p.endsWith("/") ? rel.startsWith(p) : rel === p));

if (hit) {
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        additionalContext:
          "\\u26a0 strict-tier edit (" +
          rel +
          "). Per .sdd/triage-rules.md this path ships with full TDD — RED first — and a " +
          "fresh-context review. Proceed deliberately.",
      },
    })
  );
}
process.exit(0);
`;
}

/** The `.claude/settings.json` that wires the hook. Only emitted alongside it. */
export function renderClaudeSettings(): string {
  return `${JSON.stringify(
    {
      hooks: {
        PreToolUse: [
          {
            matcher: "Edit|Write|MultiEdit",
            hooks: [
              {
                type: "command",
                command: "$CLAUDE_PROJECT_DIR/.claude/hooks/strict-path-guard.mjs",
                timeout: 10,
              },
            ],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}
