/**
 * The triage compiler: one rule list, three renderings.
 */

import type { TriageRule } from "../contracts.js";
import { DEFINITION_DIR } from "../paths.js";
import { TRIAGE_RULES_FORMAT } from "../triage/rules.js";
import type { InterviewAnswers } from "./interview.js";

/**
 * Collapse every whitespace run to a single space. Reasons are stored normalised
 * so the folded YAML block scalar (`>-`) can round-trip them: folding rejoins
 * wrapped lines with single spaces, so a reason containing a newline or a double
 * space would come back different from what went in.
 */
function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * Every rule comes from an answer or from a constant. Nothing here reads the
 * repo: ADR-0016 moved the source layout out of `detect.ts` and into the
 * interview, so `stack` is no longer an input to this function at all.
 */
export function buildTriageRules(answers: InterviewAnswers): readonly TriageRule[] {
  const rules: TriageRule[] = [];
  const seen = new Set<string>();

  const push = (rule: TriageRule): void => {
    const glob = rule.glob.trim();
    // First declaration wins. A later duplicate could never fire anyway, and
    // `parseTriageRules` refuses the document outright rather than silently
    // dropping it — so the dedupe has to happen here.
    if (glob.length === 0 || seen.has(glob)) return;
    seen.add(glob);
    rules.push({ glob, tier: rule.tier, reason: oneLine(rule.reason) });
  };

  // ── strict, most specific first ───────────────────────────────────────────
  for (const path of answers.strictPaths) {
    push({ glob: path.glob, tier: "strict", reason: path.reason });
  }

  // ── off ───────────────────────────────────────────────────────────────────
  // Placed above the broader rules so it cannot be shadowed. Only the retro log
  // is expressible as a path; the rest of the `off` row in triage-rules.md is
  // about CONTENT (typos, formatting), which a glob engine cannot see.
  push({
    glob: `${DEFINITION_DIR}/memory/retro-log.md`,
    tier: "off",
    reason:
      "An append-only record of retros that already happened. Nothing downstream reads it " +
      "as a rule, so an error in it cannot mis-gate anything.",
  });

  // ── light ─────────────────────────────────────────────────────────────────
  // The declared source roots, verbatim. A repo that named none gets no rule over
  // its code, and the `light` fallback in `classify` catches those files instead
  // — which is the same tier, arrived at honestly.
  for (const glob of answers.sourcePaths) {
    push({
      glob,
      tier: "light",
      reason:
        "Application code not claimed by a stricter rule above: reasoned before merge, a " +
        "failing happy-path test first, no full TDD ceremony.",
    });
  }
  push({
    glob: "docs/**",
    tier: "light",
    reason:
      "Documentation. Wrong here costs a reader an hour, which is real but recoverable, so " +
      "it does not earn test ceremony.",
  });
  push({
    glob: "{README,AGENTS,CLAUDE}.md",
    tier: "light",
    reason:
      `Orientation prose. AGENTS.md and CLAUDE.md are generated from ${DEFINITION_DIR}/ — edit the ` +
      "source and regenerate rather than patching them here.",
  });
  push({
    glob: `${DEFINITION_DIR}/memory/decisions.md`,
    tier: "light",
    reason:
      "ADR bodies. Accepted text is superseded rather than rewritten, so the risk lives in " +
      "the decision itself, not in the prose.",
  });

  return rules;
}

// ── `.wst/triage.yaml` ───────────────────────────────────────────────────────

const YAML_HEADER = `# Triage rules — the machine-readable form of the table in ${DEFINITION_DIR}/triage-rules.md.
# GENERATED by \`wst init\`. That table is the SOURCE; this file is compiled from it.
#
# ORDER IS PRECEDENCE. Classification is FIRST-MATCH-WINS per file, so a broad rule
# placed above a narrow one silently demotes everything the narrow one was written
# to catch — and the failure is invisible, because the change still gets *a* tier,
# just the wrong one. Most specific first.
#
# The tier of a whole CHANGE is the MAXIMUM across the files it touches: one strict
# file makes the whole change strict. Size only escalates, never de-escalates.
#
# A file that matches NO rule falls back to \`light\`. That fallback lives in code,
# not here: \`**\` will not cross a dot-leading path segment, so a trailing \`**\`
# catch-all rule would silently miss every dotfile.
`;

/** Words per line when folding a reason. Keeps the file reviewable in a diff. */
const WRAP = 76;

function foldReason(reason: string, indent: string): string {
  const words = reason.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line.length === 0) line = word;
    else if (line.length + 1 + word.length <= WRAP) line = `${line} ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line.length > 0) lines.push(line);
  return lines.map((l) => `${indent}${l}`).join("\n");
}

/**
 * A folded block scalar (`>-`) is readable and round-trips reliably for ordinary
 * prose, but only while every line sits at exactly the block indent and none of
 * them starts with a character YAML reads structurally. When the reason cannot be
 * guaranteed to survive folding, fall back to a JSON-quoted scalar: uglier, and
 * exactly correct for any string whatsoever.
 */
function foldable(reason: string): boolean {
  if (reason.length === 0) return false;
  if (reason !== oneLine(reason)) return false;
  // A folded scalar's first character must not be one YAML would read as an
  // indicator, and a `#` anywhere would start a comment when the line is re-read.
  return !/^[-?:,[\]{}#&*!|>'"%@`]/.test(reason) && !reason.includes("#");
}

export function renderTriageYaml(rules: readonly TriageRule[]): string {
  const body = rules
    .map((rule) => {
      const glob = `  - glob: ${JSON.stringify(rule.glob)}`;
      const tier = `    tier: ${rule.tier}`;
      const reason = foldable(rule.reason)
        ? `    reason: >-\n${foldReason(rule.reason, "      ")}`
        : `    reason: ${JSON.stringify(rule.reason)}`;
      return `${glob}\n${tier}\n${reason}`;
    })
    .join("\n\n");

  return `${YAML_HEADER}\nversion: ${TRIAGE_RULES_FORMAT}\n\nrules:\n${body}\n`;
}

// ── `.wst/triage-rules.md` ───────────────────────────────────────────────────

/** Markdown table cells cannot contain a raw pipe or a newline. */
function cell(text: string): string {
  return oneLine(text).replaceAll("|", "\\|");
}

export interface TriageRulesMdMeta {
  readonly date: string;
}

export function renderTriageRulesMd(
  rules: readonly TriageRule[],
  meta: TriageRulesMdMeta,
): string {
  const byTier = (tier: TriageRule["tier"]): readonly TriageRule[] =>
    rules.filter((r) => r.tier === tier);

  const applies = (tier: TriageRule["tier"], fallback: string): string => {
    const list = byTier(tier);
    if (list.length === 0) return fallback;
    return list.map((r) => `\`${cell(r.glob)}\` — ${cell(r.reason)}`).join("<br>");
  };

  const strictRow = applies(
    "strict",
    "**Nothing is strict yet.** No path was named at init. Add the core domain logic here " +
      "the moment it exists — an empty strict row is a decision to be revisited, not a " +
      "statement that nothing matters.",
  );

  return `---
id: triage-rules
generated: ${meta.date}
status: active
---
# Triage rules

Classify every change into a discipline level BEFORE work starts.

| Level | Applies to | Discipline |
| ----- | ---------- | ---------- |
| \`strict\` | ${strictRow} | **Full TDD — RED → GREEN → TRIANGULATE → REFACTOR.** Fresh-context review before it ships. No shortcuts. |
| \`light\` | ${applies("light", "standard changes not matching strict")} | A failing happy-path test first; reasoned before merge. No full ceremony. |
| \`off\` | ${applies("off", "trivial changes: typos, formatting, changelog lines")} | No ceremony. |

Default when a change matches nothing above: \`light\`.

**Tier is the MAXIMUM of the files touched** — one \`strict\` file in a diff makes the whole
change \`strict\`. Size only escalates, never de-escalates.

\`${DEFINITION_DIR}/triage-rules.md\` **is** amendable by the retro: a change that was mis-classified is
the primary evidence for editing the table.

\`${DEFINITION_DIR}/triage.yaml\` is COMPILED from this table. Change the table first, then
regenerate — never the reverse.
`;
}

/**
 * WHAT USED TO LIVE HERE: `renderStrictPathGuard` and `renderClaudeSettings`, which
 * generated an editor hook and a `.claude/settings.json` into every bootstrapped
 * repo. Removed by ADR-0010.
 *
 * Two reasons, and the second is the one that made it urgent. The settings write was
 * WHOLESALE — it replaced a repo's permissions, env and other hooks, which is why
 * `core/init/collisions.ts` had to exist (sig-0029). And it was the third copy of one
 * hook: this generator, Whetstone's own under `.claude/hooks/`, and the plugin's. The
 * three were written on three different days and had already diverged, which is
 * sig-0027 and sig-0028 for the third time.
 *
 * The plugin owns it now. It reads `.wst/triage.yaml` at run time instead of baking
 * the paths in, so it cannot go stale, and it composes with a repo's existing hooks
 * instead of overwriting them.
 */
