/**
 * The wordmark. Presentation only — no decisions, so it lives beside `cli.ts`
 * rather than in `core/`.
 *
 * Shown where a HUMAN typed the command: `wst` bare, and `wst init`. Never in
 * `gate`, `status`, `check` or `triage` — those run inside hooks and CI, where a
 * banner is output somebody has to scroll past to find the failure.
 */

export const WORDMARK = "▓▒░ whetstone";

export const TAGLINE = "a self-sharpening standards layer";

/** Two lines, aligned under the wordmark. Callers add their own trailing newline. */
export function banner(version?: string): string {
  const head = version === undefined ? WORDMARK : `${WORDMARK} ${version}`;
  return `${head}\n    ${TAGLINE}`;
}

/**
 * Generated by `scripts/sprite-to-ascii.ts` from the sprite the website uses.
 * Regenerate rather than retouch.
 *
 * Thirty columns, not the forty it was drawn at. At forty it filled half a
 * default terminal and stayed there behind every menu frame, which is a logo
 * turned into furniture. Below about twenty-four the isometric silhouette stops
 * reading as a stone.
 */
export const MARK: readonly string[] = Object.freeze([
  "                  ▒▒▒▒",
  "            ▓▒▒░░░░░░░░░▒▒▓",
  "     ▓▒▒▒░░░░░░░░░░░░░░░░▒▒▓█",
  " ▓▒░░░░░░░░░░░░░░░░▒▒▓▓███████",
  "█▓▓▓▒▓▒░░░░░░▒▓▓▓████████████",
  " ▓▓▓▓▓▓▓▓▒▓██████████████",
  "    █▓▓▓▓▓▓████████",
  "         ▓███",
]);
