/**
 * The wordmark. Presentation only, no decisions, so it lives beside `cli.ts`
 * rather than in `core/`.
 *
 * Shown where a HUMAN typed the command: `wst` bare, and `wst init`. Never in
 * `gate`, `status`, `check` or `triage`, which run inside hooks and CI, where a
 * banner is output somebody has to scroll past to find the failure.
 */

import { decodeMark, type Mark } from "./core/tui/mark.js";

export const WORDMARK = "\u2593\u2592\u2591 whetstone";

export const TAGLINE = "a self-sharpening standards layer";

/** Two lines, aligned under the wordmark. Callers add their own trailing newline. */
export function banner(version?: string): string {
  const head = version === undefined ? WORDMARK : `${WORDMARK} ${version}`;
  return `${head}\n    ${TAGLINE}`;
}

/**
 * Generated by `scripts/sprite-to-ascii.ts`. Regenerate rather than retouch.
 *
 * TWO widths of one drawing. `MARK` sits behind every menu frame, so it stays at
 * thirty columns: at forty it filled half a default terminal, and below about
 * twenty-four the isometric silhouette stops reading as a stone. `MARK_ENTRANCE`
 * owns the screen while it plays and can afford fifty-six.
 *
 * A cell carries two pixels stacked, so those thirty columns and eight rows hold
 * 30x16 SQUARE pixels rather than 30x8 stretched ones.
 *
 * Ten tones, shared by both. Rendered side by side, 8, 16 and 24 were
 * indistinguishable: the drawing is flat-shaded, so resolution is the only lever
 * that buys detail.
 */
export const MARK_PALETTE: readonly string[] = Object.freeze([
  "#1a1725",
  "#2c2935",
  "#3c3943",
  "#4a4852",
  "#656165",
  "#7b7676",
  "#8f8a86",
  "#a8a199",
  "#bdb4aa",
  "#c9bfb3",
]);

export const MARK: Mark = decodeMark(MARK_PALETTE, [
  "...................35.........",
  "................35899963......",
  ".............2579998899964....",
  "..........467999888899999975..",
  ".......4689999999999999999985.",
  "....56999999999999899999864320",
  ".57999899999999999999865333330",
  "167899999999999999864333333330",
  "166667899999999764333333333330",
  "16666567899976443333333333321.",
  "16666566666433333333333321....",
  ".3566666664333333333321.......",
  "...35666664333333321..........",
  ".....246664333321.............",
  "........354321................",
  "..........0...................",
]);

export const MARK_ENTRANCE: Mark = decodeMark(MARK_PALETTE, [
  ".....................................01.................",
  "..................................1257952...............",
  "................................25799999962.............",
  ".............................24689999999998630..........",
  ".........................01478999999988999999740........",
  "......................0147999999998787999999999840......",
  "...................135799999999877898999999999999953....",
  "................22689999999998899998899999989999999962..",
  ".............247899999999999999999989899999999999999750.",
  ".........0247899999999999999999999899999999999999765420.",
  "......0348999999999999999999999998899999999999964333330.",
  "...1469999999989999999999999999998999999999865333333331.",
  ".169999999979999999999999999999999999999864333333333331.",
  ".267899999999999999999999999999999999754333333333333331.",
  ".266667999999999999999999999999999764333333333323333331.",
  ".266666677999999999999999999998754333333333333333333331.",
  ".266666666568999999989999997664333333333333333333333330.",
  ".266666666566788999999998754433333333333333333333333210.",
  ".266666666566666799999754333333333333333333333333210....",
  ".2666666665666666677533333333323333333333333332100......",
  ".2666666666666666666333333333333333333333332100.........",
  ".0356666666666666665333333333333333333332100............",
  "...02466666666666565333333333333333333100...............",
  "......13566666666664333333333333332100..................",
  "........025666666664333333333332100.....................",
  "...........146666664333333332100........................",
  ".............0356664333332100...........................",
  "...............02464232100..............................",
  "..................11000.................................",
  "........................................................",
]);
